--CREATE DATABASE COVID_GRUPO1
--GO

 USE COVID_GRUPO1
GO

CREATE TABLE Main
(
ID INT IDENTITY(1,1) ,[key] varchar(80) NOT NULL, [date] varchar(80) NOT NULL,wikidata varchar(80) NULL,datacommons varchar(80) NULL,country_code varchar(80) NULL,country_name varchar(80) NULL,subregion1_code varchar(80) NULL,subregion1_name varchar(80) NULL,subregion2_code varchar(80) NULL,subregion2_name varchar(80) NULL,locality_code varchar(80) NULL,locality_name varchar(80) NULL,[3166-1-alpha-2] varchar(80) NULL,[3166-1-alpha-3] varchar(80) NULL,aggregation_level varchar(80) NULL,new_confirmed varchar(80) NULL,new_deceased varchar(80) NULL,new_recovered varchar(80) NULL,new_tested varchar(80) NULL,total_confirmed varchar(80) NULL,total_deceased varchar(80) NULL,total_recovered varchar(80) NULL,total_tested varchar(80) NULL,new_hospitalized varchar(80) NULL,total_hospitalized varchar(80) NULL,current_hospitalized varchar(80) NULL,new_intensive_care varchar(80) NULL,total_intensive_care varchar(80) NULL,current_intensive_care varchar(80) NULL,new_ventilator varchar(80) NULL,total_ventilator varchar(80) NULL,current_ventilator varchar(80) NULL,population varchar(80) NULL,population_male varchar(80) NULL,population_female varchar(80) NULL,rural_population varchar(80) NULL,urban_population varchar(80) NULL,largest_city_population varchar(80) NULL,clustered_population varchar(80) NULL,population_density varchar(80) NULL,human_development_index varchar(80) NULL,population_age_00_09 varchar(80) NULL,population_age_10_19 varchar(80) NULL,population_age_20_29 varchar(80) NULL,population_age_30_39 varchar(80) NULL,population_age_40_49 varchar(80) NULL,population_age_50_59 varchar(80) NULL,population_age_60_69 varchar(80) NULL,population_age_70_79 varchar(80) NULL,population_age_80_89 varchar(80) NULL,population_age_90_99 varchar(80) NULL,population_age_80_and_older varchar(80) NULL,gdp varchar(80) NULL,gdp_per_capita varchar(80) NULL,human_capital_index varchar(80) NULL,open_street_maps varchar(80) NULL,latitude varchar(80) NULL,longitude varchar(80) NULL,elevation varchar(80) NULL,area varchar(80) NULL,rural_area varchar(80) NULL,urban_area varchar(80) NULL,life_expectancy varchar(80) NULL,smoking_prevalence varchar(80) NULL,diabetes_prevalence varchar(80) NULL,infant_mortality_rate varchar(80) NULL,adult_male_mortality_rate varchar(80) NULL,adult_female_mortality_rate varchar(80) NULL,pollution_mortality_rate varchar(80) NULL,comorbidity_mortality_rate varchar(80) NULL,hospital_beds varchar(80) NULL,nurses varchar(80) NULL,physicians varchar(80) NULL,health_expenditure varchar(80) NULL,out_of_pocket_health_expenditure varchar(80) NULL,mobility_retail_and_recreation varchar(80) NULL,mobility_grocery_and_pharmacy varchar(80) NULL,mobility_parks varchar(80) NULL,mobility_transit_stations varchar(80) NULL,mobility_workplaces varchar(80) NULL,mobility_residential varchar(80) NULL,school_closing varchar(80) NULL,workplace_closing varchar(80) NULL,cancel_public_events varchar(80) NULL,restrictions_on_gatherings varchar(80) NULL,public_transport_closing varchar(80) NULL,stay_at_home_requirements varchar(80) NULL,restrictions_on_internal_movement varchar(80) NULL,international_travel_controls varchar(80) NULL,income_support varchar(80) NULL,debt_relief varchar(80) NULL,fiscal_measures varchar(80) NULL,international_support varchar(80) NULL,public_information_campaigns varchar(80) NULL,testing_policy varchar(80) NULL,contact_tracing varchar(80) NULL,emergency_investment_in_healthcare varchar(80) NULL,investment_in_vaccines varchar(80) NULL,stringency_index varchar(80) NULL,noaa_station varchar(80) NULL,noaa_distance varchar(80) NULL,average_temperature varchar(80) NULL,minimum_temperature varchar(80) NULL,maximum_temperature varchar(80) NULL,rainfall varchar(80) NULL,snowfall varchar(80) NULL,dew_point varchar(80) NULL,relative_humidity varchar(80) NULL,
CONSTRAINT PK_Main primary key clustered
([key],[date])
)


CREATE TABLE sex
(
	ID INT IDENTITY(1,1),
	[key] varchar(80) NOT NULL,
	[date] varchar(80)  NOT NULL,	
	new_confirmed_male varchar(80) NULL,
	new_confirmed_female varchar(80) NULL, 
	total_confirmed_male varchar(80) NULL,
	total_confirmed_female varchar(80) NULL, 
	new_deceased_male varchar(80) NULL, 
	new_deceased_female varchar(80) NULL, 
	total_deceased_male varchar(80) NULL, 
	total_deceased_female varchar(80) NULL, 
	new_recovered_male varchar(80) NULL, 
	new_recovered_female varchar(80) NULL, 
	total_recovered_male varchar(80) NULL, 
	total_recovered_female varchar(80) NULL, 
	new_tested_male varchar(80) NULL, 
	new_tested_female varchar(80) NULL, 
	total_tested_male varchar(80) NULL, 
	total_tested_female varchar(80) NULL, 
	new_hospitalized_male varchar(80) NULL, 
	new_hospitalized_female varchar(80) NULL, 
	total_hospitalized_male varchar(80) NULL, 
	total_hospitalized_female varchar(80) NULL, 
	current_hospitalized_male varchar(80) NULL,
	current_hospitalized_female varchar(80) NULL, 
	new_intensive_care_male varchar(80) NULL, 
	new_intensive_care_female varchar(80) NULL, 
	total_intensive_care_male varchar(80) NULL, 
	total_intensive_care_female varchar(80) NULL, 
	current_intensive_care_male varchar(80) NULL, 
	current_intensive_care_female varchar(80) NULL, 
	new_ventilator_male varchar(80) NULL, 
	new_ventilator_female varchar(80) NULL, 
	total_ventilator_male varchar(80) NULL, 
	total_ventilator_female varchar(80) NULL, 
	current_ventilator_male varchar(80) NULL, 
	current_ventilator_female varchar(80) NULL,
	Foreign key ([key],[date]) references Main([key],[date])
)




create table Age
(
	ID INT IDENTITY(1,1),
	[date] varchar(80)  NOT NULL,
	[key] varchar(80)  NOT NULL,
	new_confirmed_age_00 varchar(80) NULL,
	new_confirmed_age_01 varchar(80) NULL, 
	new_confirmed_age_02 varchar(80) NULL, 
	new_confirmed_age_03 varchar(80) NULL, 
	new_confirmed_age_04 varchar(80) NULL, 
	new_confirmed_age_05 varchar(80) NULL, 
	new_confirmed_age_06 varchar(80) NULL, 
	new_confirmed_age_07 varchar(80) NULL, 
	new_confirmed_age_08 varchar(80) NULL, 
	new_confirmed_age_09 varchar(80) NULL, 
	total_confirmed_age_00 varchar(80) NULL, 
	total_confirmed_age_01 varchar(80) NULL, 
	total_confirmed_age_02 varchar(80) NULL, 
	total_confirmed_age_03 varchar(80) NULL, 
	total_confirmed_age_04 varchar(80) NULL, 
	total_confirmed_age_05 varchar(80) NULL, 
	total_confirmed_age_06 varchar(80) NULL, 
	total_confirmed_age_07 varchar(80) NULL, 
	total_confirmed_age_08 varchar(80) NULL, 
	total_confirmed_age_09 varchar(80) NULL, 
	new_deceased_age_00 varchar(80) NULL, 
	new_deceased_age_01 varchar(80) NULL, 
	new_deceased_age_02 varchar(80) NULL, 
	new_deceased_age_03 varchar(80) NULL, 
	new_deceased_age_04 varchar(80) NULL, 
	new_deceased_age_05 varchar(80) NULL, 
	new_deceased_age_06 varchar(80) NULL, 
	new_deceased_age_07 varchar(80) NULL, 
	new_deceased_age_08 varchar(80) NULL, 
	new_deceased_age_09 varchar(80) NULL, 
	total_deceased_age_00 varchar(80) NULL, 
	total_deceased_age_01 varchar(80) NULL, 
	total_deceased_age_02 varchar(80) NULL, 
	total_deceased_age_03 varchar(80) NULL, 
	total_deceased_age_04 varchar(80) NULL, 
	total_deceased_age_05 varchar(80) NULL, 
	total_deceased_age_06 varchar(80) NULL, 
	total_deceased_age_07 varchar(80) NULL, 
	total_deceased_age_08 varchar(80) NULL, 
	total_deceased_age_09 varchar(80) NULL, 
	new_recovered_age_00 varchar(80) NULL, 
	new_recovered_age_01 varchar(80) NULL, 
	new_recovered_age_02 varchar(80) NULL, 
	new_recovered_age_03 varchar(80) NULL, 
	new_recovered_age_04 varchar(80) NULL, 
	new_recovered_age_05 varchar(80) NULL, 
	new_recovered_age_06 varchar(80) NULL, 
	new_recovered_age_07 varchar(80) NULL, 
	new_recovered_age_08 varchar(80) NULL, 
	new_recovered_age_09 varchar(80) NULL, 
	total_recovered_age_00 varchar(80) NULL, 
	total_recovered_age_01 varchar(80) NULL, 
	total_recovered_age_02 varchar(80) NULL, 
	total_recovered_age_03 varchar(80) NULL, 
	total_recovered_age_04 varchar(80) NULL, 
	total_recovered_age_05 varchar(80) NULL, 
	total_recovered_age_06 varchar(80) NULL, 
	total_recovered_age_07 varchar(80) NULL, 
	total_recovered_age_08 varchar(80) NULL, 
	total_recovered_age_09 varchar(80) NULL, 
	new_tested_age_00 varchar(80) NULL, 
	new_tested_age_01 varchar(80) NULL, 
	new_tested_age_02 varchar(80) NULL, 
	new_tested_age_03 varchar(80) NULL, 
	new_tested_age_04 varchar(80) NULL, 
	new_tested_age_05 varchar(80) NULL, 
	new_tested_age_06 varchar(80) NULL, 
	new_tested_age_07 varchar(80) NULL, 
	new_tested_age_08 varchar(80) NULL, 
	new_tested_age_09 varchar(80) NULL, 
	total_tested_age_00 varchar(80) NULL, 
	total_tested_age_01 varchar(80) NULL, 
	total_tested_age_02 varchar(80) NULL, 
	total_tested_age_03 varchar(80) NULL, 
	total_tested_age_04 varchar(80) NULL, 
	total_tested_age_05 varchar(80) NULL, 
	total_tested_age_06 varchar(80) NULL, 
	total_tested_age_07 varchar(80) NULL, 
	total_tested_age_08 varchar(80) NULL, 
	total_tested_age_09 varchar(80) NULL, 
	new_hospitalized_age_00 varchar(80) NULL, 
	new_hospitalized_age_01 varchar(80) NULL, 
	new_hospitalized_age_02 varchar(80) NULL, 
	new_hospitalized_age_03 varchar(80) NULL, 
	new_hospitalized_age_04 varchar(80) NULL, 
	new_hospitalized_age_05 varchar(80) NULL, 
	new_hospitalized_age_06 varchar(80) NULL, 
	new_hospitalized_age_07 varchar(80) NULL, 
	new_hospitalized_age_08 varchar(80) NULL, 
	new_hospitalized_age_09 varchar(80) NULL, 
	total_hospitalized_age_00 varchar(80) NULL, 
	total_hospitalized_age_01 varchar(80) NULL, 
	total_hospitalized_age_02 varchar(80) NULL, 
	total_hospitalized_age_03 varchar(80) NULL, 
	total_hospitalized_age_04 varchar(80) NULL, 
	total_hospitalized_age_05 varchar(80) NULL, 
	total_hospitalized_age_06 varchar(80) NULL, 
	total_hospitalized_age_07 varchar(80) NULL, 
	total_hospitalized_age_08 varchar(80) NULL,
	total_hospitalized_age_09 varchar(80) NULL,
	current_hospitalized_age_00 varchar(80) NULL,
	current_hospitalized_age_01 varchar(80) NULL,
	current_hospitalized_age_02 varchar(80) NULL,
	current_hospitalized_age_03 varchar(80) NULL,
	current_hospitalized_age_04 varchar(80) NULL,
	current_hospitalized_age_05 varchar(80) NULL,
	current_hospitalized_age_06 varchar(80) NULL,
	current_hospitalized_age_07 varchar(80) NULL,
	current_hospitalized_age_08 varchar(80) NULL,
	current_hospitalized_age_09 varchar(80) NULL,
	new_intensive_care_age_00 varchar(80) NULL,
	new_intensive_care_age_01 varchar(80) NULL,
	new_intensive_care_age_02 varchar(80) NULL,
	new_intensive_care_age_03 varchar(80) NULL,
	new_intensive_care_age_04 varchar(80) NULL,
	new_intensive_care_age_05 varchar(80) NULL,
	new_intensive_care_age_06 varchar(80) NULL,
	new_intensive_care_age_07 varchar(80) NULL,
	new_intensive_care_age_08 varchar(80) NULL,
	new_intensive_care_age_09 varchar(80) NULL,
	total_intensive_care_age_00 varchar(80) NULL, 
	total_intensive_care_age_01 varchar(80) NULL,
	total_intensive_care_age_02 varchar(80) NULL,
	total_intensive_care_age_03 varchar(80) NULL,
	total_intensive_care_age_04 varchar(80) NULL,
	total_intensive_care_age_05 varchar(80) NULL, 
	total_intensive_care_age_06 varchar(80) NULL,
	total_intensive_care_age_07 varchar(80) NULL,
	total_intensive_care_age_08 varchar(80) NULL,
	total_intensive_care_age_09 varchar(80) NULL,
	current_intensive_care_age_00 varchar(80) NULL,
	current_intensive_care_age_01 varchar(80) NULL,
	current_intensive_care_age_02 varchar(80) NULL,
	current_intensive_care_age_03 varchar(80) NULL,
	current_intensive_care_age_04 varchar(80) NULL,
	current_intensive_care_age_05 varchar(80) NULL,
	current_intensive_care_age_06 varchar(80) NULL,
	current_intensive_care_age_07 varchar(80) NULL,
	current_intensive_care_age_08 varchar(80) NULL,
	current_intensive_care_age_09 varchar(80) NULL,
	new_ventilator_age_00 varchar(80) NULL,
	new_ventilator_age_01 varchar(80) NULL,
	new_ventilator_age_02 varchar(80) NULL,
	new_ventilator_age_03 varchar(80) NULL,
	new_ventilator_age_04 varchar(80) NULL,
	new_ventilator_age_05 varchar(80) NULL,
	new_ventilator_age_06 varchar(80) NULL,
	new_ventilator_age_07 varchar(80) NULL,
	new_ventilator_age_08 varchar(80) NULL,
	new_ventilator_age_09 varchar(80) NULL,
	total_ventilator_age_00 varchar(80) NULL,
	total_ventilator_age_01 varchar(80) NULL,
	total_ventilator_age_02 varchar(80) NULL,
	total_ventilator_age_03 varchar(80) NULL,
	total_ventilator_age_04 varchar(80) NULL,
	total_ventilator_age_05 varchar(80) NULL,
	total_ventilator_age_06 varchar(80) NULL,
	total_ventilator_age_07 varchar(80) NULL,
	total_ventilator_age_08 varchar(80) NULL,
	total_ventilator_age_09 varchar(80) NULL,
	current_ventilator_age_00 varchar(80) NULL,
	current_ventilator_age_01 varchar(80) NULL,
	current_ventilator_age_02 varchar(80) NULL,
	current_ventilator_age_03 varchar(80) NULL, 
	current_ventilator_age_04 varchar(80) NULL, 
	current_ventilator_age_05 varchar(80) NULL, 
	current_ventilator_age_06 varchar(80) NULL, 
	current_ventilator_age_07 varchar(80) NULL, 
	current_ventilator_age_08 varchar(80) NULL, 
	current_ventilator_age_09 varchar(80) NULL, 
	age_bin_00 varchar(80) NULL, 
	age_bin_01 varchar(80) NULL, 
	age_bin_02 varchar(80) NULL,
	age_bin_03 varchar(80) NULL, 
	age_bin_04 varchar(80) NULL, 
	age_bin_05 varchar(80) NULL, 
	age_bin_06 varchar(80) NULL, 
	age_bin_07 varchar(80) NULL, 
	age_bin_08 varchar(80) NULL, 
	age_bin_09 varchar(80) NULL,
	Foreign key ([key],[date]) references Main([key],[date])
)

